openapi: 3.0.0
info:
  description: |-
    Urbs 灰度平台灰度策略服务
  version: 1.2.0
  title: urbs-setting
servers:
  - url: https://urbs-setting:8443
    description: 这是内部服务，请替换为实际 URL
tags:
  - name: Version
    description: 获取 urbs-setting 服务版本信息
  - name: User
    description: User 用户相关接口
  - name: Group
    description: Group 群组相关接口
  - name: Product
    description: Product 产品相关接口
  - name: Label
    description: Label 灰度标签相关接口
  - name: Module
    description: Module 产品模块相关接口
  - name: Setting
    description: Setting 产品模块配置项相关接口
components:
  parameters:
    HeaderAuthorization:
      in: header
      name: Authorization
      description: '请求 JWT token, 格式如: `Bearer xxx`'
      required: true
      schema:
        type: string
    PathUID:
      in: path
      name: uid
      description: 用户/群组 uid
      required: true
      schema:
        type: string
    PathHID:
      in: path
      name: uid
      description: 标签/配置项 hid
      required: true
      schema:
        type: string
    QueryProduct:
      in: query
      name: product
      description: 产品名称
      required: true
      schema:
        type: string
    QueryPageSize:
      in: query
      name: pageSize
      description: 分页大小，默认为 10，(1-1000]
      required: false
      schema:
        type: integer
        format: int32
        default: 10
        example: 20
    QueryPageToken:
      in: query
      name: pageToken
      description: 分页请求标记，来自于响应结果的 nextPageToken
      required: false
      schema:
        title: pageToken
        type: string
        default: ""
        example: "2020-03-13T11%3A59%3A48Z"
  securitySchemes:
    HeaderAuthorizationJWT:
      name: Authorization
      type: http
      scheme: bearer
      bearerFormat: JWT
      in: header

  schemas:
    NextPageToken:
      title: nextPageToken
      type: string
      description: 用于分页查询时用于获取下一页数据的 token，当为空值时表示没有下一页了
      example: ""
    TotalSize:
      title: totalSize
      type: integer
      format: int64
      description: 当前分页查询的总数据量
      example: 1
    Version:
      type: object
      properties:
        name:
          type: string
          description: 服务名称
          example: urbs-setting
        version:
          type: string
          description: 当前版本
          example: v1.2.0
        gitSHA1:
          type: string
          description: git commit hash
          example: cd7e82a
        buildTime:
          type: string
          format: date-time
          description: 打包构建时间
          example: 2020-03-25T06:24:25Z
    CacheLabelInfo:
      type: object
      properties:
        l:
          type: string
          description: 灰度标签名称
          example: beta
        cls:
          type: array
          description: 灰度标签适用的 Clients 客户端类型列表，当列表为空时表示全适用
          example: ["ios", "android", "web"]
          items:
            type: string
        chs:
          type: array
          description: 灰度标签适用的 Channels 版本通道列表，当列表为空时表示全适用
          example: ["stable", "beta", "dev"]
          items:
            type: string
    LabelInfo:
      type: object
      properties:
        hid:
          type: string
          description: 灰度标签的 hid
          example: AwAAAAAAAAB25V_QnbhCuRwF
        product:
          type: string
          description: 灰度标签所属的产品名称
          example: teambition
        name:
          type: string
          description: 灰度标签名称，同一产品下唯一（不能重名）
          example: beta
        desc:
          type: string
          description: 灰度标签描述
        channels:
          type: array
          description: 灰度标签适用版本通道
          example: ["beta"]
          items:
            type: string
        clients:
          type: array
          description: 灰度标签适用客户端类型
          example: ["web"]
          items:
            type: string
        status:
          type: integer
          format: int64
          description: 灰度标签状态（暂未支持）
          example: 0
        created_at:
          type: string
          format: date-time
          description: 灰度标签创建时间
          example: 2020-03-25T06:24:25Z
        updated_at:
          type: string
          format: date-time
          description: 灰度标签更新时间
          example: 2020-03-25T06:24:25Z
        offline_at:
          type: string
          format: date-time
          description: 灰度标签下线时间
          default: null
          example: null
    MySetting:
      type: object
      properties:
        hid:
          type: string
          description: 配置项的 hid
          example: AwAAAAAAAAB25V_QnbhCuRwF
        module:
          type: string
          description: 配置项所属的功能模块名称
          example: task
        name:
          type: string
          description: 配置项名称，同一产品功能模块下唯一（不能重名）
          example: task-share
        value:
          type: string
          description: 配置项值
          example: disable
        last_value:
          type: string
          description: 配置项值
          example: ""
        created_at:
          type: string
          format: date-time
          description: 灰度标签创建时间
          example: 2020-03-25T06:24:25Z
        updated_at:
          type: string
          format: date-time
          description: 灰度标签更新时间
          example: 2020-03-25T06:24:25Z
    Group:
      type: object
      properties:
        uid:
          type: string
          description: 群组的 uid
          example: 5e82d747fe02a50021d339f3
        user:
          type: string
          description: 群组类型
          example: organization
        desc:
          type: string
          description: 群组的描述
        sync_at:
          type: integer
          format: int64
          description: 群组成员同步时间点，1970 以来的秒数
          example: 1585636012
        created_at:
          type: string
          format: date-time
          description: 灰度标签创建时间
          example: 2020-03-25T06:24:25Z
        updated_at:
          type: string
          format: date-time
          description: 灰度标签更新时间
          example: 2020-03-25T06:24:25Z
    GroupMember:
      type: object
      properties:
        user:
          type: string
          description: 群组成员的用户 uid
          example: 5e82d747fe02a50021d339f3
        sync_at:
          type: integer
          format: int64
          description: 该群组成员同步时间，1970 以来的秒数
          example: 1585636012
        created_at:
          type: string
          format: date-time
          description: 该群组成员添加时间
          example: 2020-03-25T06:24:25Z

  requestBodies:
    UsersBody:
      required: true
      description: 批量添加用户请求数据
      content:
        application/json:
          schema:
            type: object
            properties:
              users:
                type: array
                description: 用户 uid 数组
                required: true
                example: ["50c32afae8cf1439d35a87e6", "5e69a9bd6ac3cd00213ea969"]
                items:
                  type: string
    GroupsBody:
      required: true
      description: 批量添加群组请求数据
      content:
        application/json:
          schema:
            type: object
            properties:
              groups:
                type: array
                description: 群组信息数组
                required: true
                example: [{"uid": "50c32afae8cf1439d35a87e6", "kind": "organization"}]
                items:
                  type: object
                  properties:
                    uid:
                      type: string
                      description: 群组 uid
                      required: true
                    kind:
                      type: string
                      description: 群组类型
                      required: true
                    desc:
                      type: string
                      description: 群组描述
                      required: false
    GroupUpdateBody:
      required: true
      description: 更新群组请求数据
      content:
        application/json:
          schema:
            type: object
            properties:
              sync_at:
                type: integer
                title: sync_at
                format: int64
                description: 群组成员同步时间点，1970 以来的秒数
              desc:
                type: string
                title: desc
                description: 群组描述
            example: {"sync_at": 1585638012}

  responses:
    ErrorResponse:
      description: 标准错误返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: 错误代号
                example: NotFound
              message:
                type: string
                description: 错误详情
                example: some thing not found
    BoolRes:
      description: 标准 Boolean 类返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                type: boolean
                description: 是否成功
                example: true
    Version:
      description: version 返回结果
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Version"
    Healthz:
      description: Healthz 返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              db_connect:
                type: boolean
                description: 是否连接了数据库
                example: true
    CacheLabelsInfo:
      description: 用于网关的用户灰度标签列表返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              timestamp:
                type: integer
                format: int64
                description: 灰度标签列表缓存生成时间，1970 以来的秒数
                example: 1585129360
              result:
                type: array
                description: 灰度标签列表
                items:
                  $ref: "#/components/schemas/CacheLabelInfo"
    LabelsInfoRes:
      description: 用户或群组被指派的标签列表返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              totalSize:
                $ref: "#/components/schemas/TotalSize"
              nextPageToken:
                $ref: "#/components/schemas/NextPageToken"
              result:
                type: array
                items:
                  $ref: "#/components/schemas/LabelInfo"
    MySettingsRes:
      description: 用户或群组被指派的配置项列表返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              nextPageToken:
                $ref: "#/components/schemas/NextPageToken"
              result:
                type: array
                items:
                  $ref: "#/components/schemas/MySetting"
    GroupsRes:
      description: 群组列表返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              totalSize:
                $ref: "#/components/schemas/TotalSize"
              nextPageToken:
                $ref: "#/components/schemas/NextPageToken"
              result:
                type: array
                items:
                  $ref: "#/components/schemas/Group"
    GroupRes:
      description: 单个群组返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                $ref: "#/components/schemas/Group"
    GroupMembersRes:
      description: 群组成员列表返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              totalSize:
                $ref: "#/components/schemas/TotalSize"
              nextPageToken:
                $ref: "#/components/schemas/NextPageToken"
              result:
                type: array
                items:
                  $ref: "#/components/schemas/GroupMember"
paths:
