addr: ":8080"
cert_file:
key_file:
logger:
  level: debug
mysql:
  host: localhost:3306
  user: root
  password: password
  database: urbs
  parameters: loc=UTC&readTimeout=10s&writeTimeout=10s&timeout=10s&multiStatements=false
  max_idle_conns: 8
  max_open_conns: 64
mysql_read:
  host: localhost:3306
  user: root
  password: password
  database: urbs
  parameters: loc=UTC&readTimeout=10s&writeTimeout=10s&timeout=10s&multiStatements=false
  max_idle_conns: 8
  max_open_conns: 64
channels:
  - stable
  - beta
  - dev
clients:
  - web
  - ios
  - android
  - windows
  - macos
cache_label_expire: 5m
auth_keys:
  - kqGuLsiKT1J5ANFDKXUHc2lAYfdzWBnriL1iHgBbYQ
hid_key: q7FltzZWfvGIrdEdHYY # 一旦设定，尽量不要改变，否则派生出去的 HID 无法识别
open_trust:
  otid: ""
  private_keys: []
  domain_public_keys:
  - '{"kty":"RSA","alg":"PS256","e":"AQAB","kid":"4PblNZYSnOsy8sD6SHZPEl6DCqEerpgfi_sPxthHpWM","n":"0FjUWU9H6P9JTe3ZFOGxoVlYKFlzr98N44vIvjvvLVM1FU3MECJeTpztgnONZKelBO2YSY29v1mTl_PLWxVsn-gwkRczp1F5ogvt64dkPpaSdzpOLS1aKhqJSpVJp-D0lJWJ4ksEvyvM1hMNe9F3gbI6yyLigPhfF6qPdS2PxbFdilX4TmvrmViFnkVT31L4aXVuaEg9juLfxbIs-lnbvE9_L0a-zm-PfN-sLP3_SrPtUBLRH-cVgiMc43eXqU1H5AqJ0XzPHdrwzTRFiZuLsyaI2zj67D2x9Wwn8ze2OeP_B6th97XQfS_6zJ5BDs_VPoQi19F0Ts3dWnlXi2CrhQ"}'
